/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaclient1;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;


/**
 *
 * @author DELL
 */
public class table extends javax.swing.JFrame {

   

  
    public table() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Connection state	", " source address	", "source port", " dest. address	", "dest. port "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tt.setText("refresh");
        tt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(tt)
                .addContainerGap(521, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttActionPerformed
        // TODO add your handling code here:
        
        
                                       

                                       
        // TODO add your handling code here:
                      try {                                         
            // TODO add your handling code here:
            URL url = null;
            try {
                url = new URL ("http://localhost/phphome/tcp_test.php");
            } catch (MalformedURLException ex) {
                Logger.getLogger(part2.class.getName()).log(Level.SEVERE, null, ex);
            }
            URLConnection urlc = url.openConnection();
            urlc.setAllowUserInteraction(true);
            urlc.setDoInput(true);
            urlc.setDoOutput(true);
            
            //String str = "name=Manar";
            OutputStream os = null;
            try {
                os = urlc.getOutputStream();
            } catch (IOException ex) {
                Logger.getLogger(part2.class.getName()).log(Level.SEVERE, null, ex);
            }
            //byte [] data = str.getBytes();
            //os.write(data);
            
            InputStream is = urlc.getInputStream();
            String s = "";
            int ch=-1;
            while((ch = is.read()) != -1) {
                
             // System.out.print((char)ch);
          s = s+ (char)ch ;
          
          
          
          

            }
            String[] arr = s.split(";");
             String[] arr1 = s.split("1");
           // System.out.print(arr[12]);
             
            String[] dataRow = s.split(";");
            
              String[] ii = null ;

             DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                       //   List oo= new ArrayList<String>();
        // List<String> wordList = Arrays.asList(dataRow); 
              List<String> wordList = Arrays.asList(dataRow);  
                     Vector<String> v = new Vector<String>();
  Vector<String> pp = new Vector<String>();
          
         // Use the addAll method of the Collections to add
         // all array elements to the vector object
         
         
        Collections.addAll(v, dataRow);
        Collections.addAll(pp, dataRow);

       // for (Object o : v) {
   
    // model.addRow(v);
    
  
//}



          int z=0 ; 
//int i=6 ;             
             // v.removeAllElements();
              Object[] tableLines = new Object [pp.size()/6] ;
              int zz = pp.size();
         //    while (zz!=0){
                   for(int i = 0; i < pp.size();  i=i+6){
                 
                 

                //model.addRow(v);
     // v.remove(0);
     // model.addRow(v);
     v.removeAllElements();
     tableLines[z]=dataRow[i]+"/" +dataRow[i+1]+"/"+dataRow[i+2]+"/"+dataRow[i+3]+"/"+dataRow[i+4]+"/"+dataRow[i+5] ;
         /*v.add(dataRow[i]);
         v.add(dataRow[i+1]);
         v.add(dataRow[i+2]);
         v.add(dataRow[i+3]);
         v.add(dataRow[i+4]);
         v.add(dataRow[i+5]);*/
           z++ ; 
         //model.addRow(v);
       //  zz=zz-6 ; 
        // i=i+6 ; 
        
         
        
             
                        //}
          
              }
                
                          for (Object tableLine : tableLines) {
                              String line = tableLine.toString();
                              String[] dataRow1 = line.split("/");
                              model.addRow(dataRow1);
                          }
                          //  dataRow = dataRow.copyOfRange(dataRow, 1, arr.length);
                 
             


                 

            
                
            
             

            
            
        } catch (IOException ex) {
            Logger.getLogger(part2.class.getName()).log(Level.SEVERE, null, ex);}
        
    }//GEN-LAST:event_ttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JButton tt;
    // End of variables declaration//GEN-END:variables
}
